name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: dist
          account_name: demotestmicrofrontend
          container_name: reactapp
          sas_token: sp=r&st=2024-04-04T09:32:19Z&se=2024-04-04T17:32:19Z&spr=https&sv=2022-11-02&sr=c&sig=NzGRbRf582aVrOgUjYwUPykCov7U67bm9fk%2FAJ%2B5wwo%3D
          overwrite: 'true'
